struct sysopr_t {
    uint8_t adcChkInterval;
    uint8_t gpioChkInterval;
    uint8_t sleepEnable;
    uint8_t wakeupEnable;
    uint8_t sleepRegularity;
    uint8_t sleepHour;
    uint8_t sleepMinute;
    uint8_t sleepSecond;
    uint8_t wakeupRegularity;
    uint8_t wakeupHour;
    uint8_t wakeupMinute;
    uint8_t wakeupSecond;
    uint8_t rcdPicEnable;
    uint8_t rcdPicEvent;
    uint8_t rcdPicSize;
    uint8_t rcdPicInterval;
    uint8_t rcdAvEnable;
    uint8_t rcdAvEvent;
    uint8_t rcdAvSize;
    uint8_t rcdAvTime;
    uint8_t pushEnable;
    uint8_t alarmEnable;
    uint8_t wifiEnable;
    uint8_t ircut;
};
